### ISSUE TITLE
Building up Frame App

### ISSUE THREAD

**Issue by westeezy** [westeezy/ReactJS-Bootcamp#7]
- CSS - Base styles and classes to use throughout
- Header - just a logo and empty input styled properly
- Body - Component that says HelloWorld
- Movie JSON Files - Movie List preferably, maybe from IMDB
- Basic test that that all components render
- http://codepen.io/anon/pen/Nqyxeo

**Comment by westeezy** [comment]
Added a header to Day0 so far. Will branch off there and create the skeleton and push back in and update all the days.

**Comment by stephenmelnicki** [comment]
Added some integration with movie mock data via component props. Mostly highlighting props provided to components via `constructor(props) { ... }`

**Comment by westeezy** [comment]
Yeah thats still WIP I was going to build it up a little then tear it down so we can build in front of everyone.  Also you should use a spread for that with `constructor(...args)` as they come into the method that way

**Comment by stephenmelnicki** [comment]
I can dig it. Just pushed up a [commit](https://github.com/westeezy/ReactJS-Bootcamp/commit/519d772357fb2db1f3221fcc97b8209bbac0c1f1) to the `day2` branch with the `constructor()` business. Want me to revert it?

**Comment by westeezy** [comment]
https://github.com/westeezy/ReactJS-Bootcamp/commit/8fd867611242b762d3a1c049c251d7ac604808d6

That's what it should ideally be. Yeah rollback day2 as those branches are all being changed. The slides will exist for each day on all branches but the app will be being built up so master and day0 are currently the focus of that refactor. Anything past those days I will be deleting the branch and recreating within the next few days
